//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermercado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulos()
        {
            this.Lineas = new HashSet<Lineas>();
        }
    
        public int idArticulo { get; set; }
        public int idProveedor { get; set; }
        public string detalle { get; set; }
        public string marca { get; set; }
        public string presentacion { get; set; }
        public Nullable<double> precioCompra { get; set; }
        public Nullable<double> precioVenta { get; set; }
        public Nullable<int> stock { get; set; }
        public string barcode { get; set; }
        public bool eliminado { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lineas> Lineas { get; set; }
    }
}
